// AUTO-GENERATED by update-recess-schedule.py — do not edit by hand.
// Source: newest לוז_פגרה_מתעדכן_לאתר*.docx (OneDrive דף מסרים / Downloads).
// Recess format: dated items only, grouped by arena → day. Background
// ("תמונת מצב") content lives in the sekira tabs, not here.

export interface RecessScheduleSource { label: string; url?: string; }
export interface RecessScheduleItem {
  tag?: string;
  title: string;
  summary?: string;
  detail?: string;
  sources: RecessScheduleSource[];
}
export interface RecessScheduleDay { day: string; items: RecessScheduleItem[]; }
export type RecessArenaId = 'knesset' | 'gov' | 'court' | 'events';
export interface RecessScheduleArena { arena: RecessArenaId; label: string; days: RecessScheduleDay[]; }

export const RECESS_SCHEDULE_TITLE = `לו"ז לתקופת הפגרה 2.8–23.8`;

export const RECESS_SCHEDULE: RecessScheduleArena[] = [
  {
    arena: 'knesset',
    label: `כנסת`,
    days: [
      {
        day: `יום ראשון, 2.8`,
        items: [
          {
            tag: `ישיבה חסויה`,
            title: `ועדת החוץ והביטחון — ישיבה חסויה (12:00)`,
            summary: `נושא הישיבה לא פורסם.`,
            sources: [],
          },
        ],
      },
      {
        day: `יום שלישי, 4.8`,
        items: [
          {
            tag: `דיון`,
            title: `ועדת הכספים — פניות תקציביות שנותרו ללא דיון`,
            summary: `בדיון ב-29.7 הונחו 33 פניות בהיקף כ-16 מיליארד ש"ח, מהן כ-653 מיליון ש"ח כספים קואליציוניים. הדיון ננעל לפני שהוועדה הגיעה לרוב הפניות בחינוך ובהתיישבות.`,
            detail: `טרם פורסמה הודעה רשמית על כינוס. לפי מידע שהתקבל, באוצר נערכים להעלאת הפניות שנותרו ביום שלישי. פירוט הפניות שנותרו — בטאב כנסת בסקירה.`,
            sources: [],
          },
        ],
      },
      {
        day: `יום חמישי, 6.8`,
        items: [
          {
            tag: `דיון`,
            title: `ועדת החינוך — היערכות לפתיחת שנת הלימודים תשפ"ז (11:00)`,
            summary: `הוועדה מתכנסת בעקבות פנייה מ-23.7 של אגודת היועצים החינוכיים בישראל ליו"ר הוועדה ח"כ צבי סוכות, המבקשת דיונים בחיזוק מערך הייעוץ החינוכי ובהגדלת תקני שפ"י.`,
            sources: [],
          },
        ],
      },
    ],
  },
  {
    arena: 'gov',
    label: `ממשלה`,
    days: [
    ],
  },
  {
    arena: 'court',
    label: `בג"ץ`,
    days: [
    ],
  },
  {
    arena: 'events',
    label: `אירועים בולטים`,
    days: [
      {
        day: `יום שלישי, 4.8`,
        items: [
          {
            tag: `אירוע`,
            title: `פריימריז המפלגה הדמוקרטית לסנאט במישיגן`,
            summary: `התאריך טרם אומת.`,
            sources: [],
          },
        ],
      },
      {
        day: `יום רביעי, 12.8`,
        items: [
          {
            tag: `אירוע`,
            title: `פרסום אתרי ההצבעה הסופיים בפריימריז בליכוד`,
            summary: `לפי לוח הזמנים הרשמי של הפריימריז בליכוד.`,
            sources: [
              { label: `ערוץ 14`, url: `https://www.c14.co.il/article/1628487` },
            ],
          },
        ],
      },
      {
        day: `יום שני, 17.8`,
        items: [
          {
            tag: `אירוע`,
            title: `פריימריז בליכוד`,
            summary: `הקלפיות פתוחות 10:00–20:00. זכות הצבעה — מי שהתפקדו עד 17.4.2025; זכות התמודדות — מי שהתפקדו עד 21.7.2023.`,
            sources: [
              { label: `ערוץ 14`, url: `https://www.c14.co.il/article/1628487` },
            ],
          },
        ],
      },
      {
        day: `יום חמישי, 20.8`,
        items: [
          {
            tag: `אירוע`,
            title: `פרסום תוצאות הפריימריז בליכוד`,
            summary: `לפי לוח הזמנים הרשמי של הפריימריז בליכוד.`,
            sources: [
              { label: `ערוץ 14`, url: `https://www.c14.co.il/article/1628487` },
            ],
          },
        ],
      },
      {
        day: `יום ראשון, 23.8`,
        items: [
          {
            tag: `דדליין`,
            title: `מועד אחרון להגשת ערעורים על תוצאות הפריימריז`,
            summary: `לפי לוח הזמנים הרשמי של הפריימריז בליכוד.`,
            sources: [
              { label: `ערוץ 14`, url: `https://www.c14.co.il/article/1628487` },
            ],
          },
        ],
      },
    ],
  },
];
