// AUTO-GENERATED by update-recess-schedule.py — do not edit by hand.
// Source: newest לוז_פגרה_מתעדכן_לאתר*.docx (OneDrive דף מסרים / Downloads).
// Recess format: dated items only, grouped by arena → day. Background
// ("תמונת מצב") content lives in the sekira tabs, not here.

export interface RecessScheduleSource { label: string; url?: string; }
export interface RecessScheduleItem {
  tag?: string;
  title: string;
  summary?: string;
  detail?: string;
  sources: RecessScheduleSource[];
}
export interface RecessScheduleDay { day: string; items: RecessScheduleItem[]; }
export type RecessArenaId = 'knesset' | 'gov' | 'court' | 'events';
export interface RecessScheduleArena { arena: RecessArenaId; label: string; days: RecessScheduleDay[]; }

export const RECESS_SCHEDULE_TITLE = `לו"ז לתקופת הפגרה 17.9–4.10`;

export const RECESS_SCHEDULE: RecessScheduleArena[] = [
  {
    arena: 'knesset',
    label: `כנסת`,
    days: [
    ],
  },
  {
    arena: 'gov',
    label: `ממשלה`,
    days: [
    ],
  },
  {
    arena: 'court',
    label: `בג"ץ`,
    days: [
      {
        day: `יום חמישי, 24.9`,
        items: [
          {
            tag: `דיון`,
            title: `בג"ץ: דיון בעתירת ההעברות התקציביות בפגרה`,
            sources: [
              { label: `דבר, 24.8.26`, url: `https://www.davar1.co.il/694431/` },
            ],
          },
        ],
      },
    ],
  },
  {
    arena: 'events',
    label: `אירועים בולטים`,
    days: [
      {
        day: `יום ראשון, 20.9`,
        items: [
          {
            tag: `חופשה`,
            title: `ערב יום כיפור: אין לימודים; יום עבודה, מקוצר במקומות עבודה רבים`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
              { label: `כל זכות, זכותון עובדים בחגים`, url: `https://www.kolzchut.org.il/he/%D7%96%D7%9B%D7%95%D7%AA%D7%95%D7%9F_%D7%A2%D7%95%D7%91%D7%93%D7%99%D7%9D_%D7%91%D7%97%D7%92%D7%99%D7%9D` },
            ],
          },
        ],
      },
      {
        day: `יום שני, 21.9`,
        items: [
          {
            tag: `חופשה`,
            title: `יום כיפור`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
        ],
      },
      {
        day: `יום שלישי, 22.9`,
        items: [
          {
            tag: `חופשה`,
            title: `22-24.9 · ימי הגשר: אין לימודים; ימי עבודה רגילים במשק`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
          {
            tag: `אירוע`,
            title: `22-28.9 · הדיון הכללי בעצרת הכללית של האו"ם`,
            summary: `טרם ידוע מה המועד הספציפי שבו נתניהו צפוי לנאום.`,
            sources: [
              { label: `האו"ם, נשיאות העצרת הכללית`, url: `https://www.un.org/pga/81/event/general-debate-of-the-eighty-first-session-of-the-general-assembly/` },
              { label: `i24NEWS, 14.9.26`, url: `https://www.i24news.tv/he/news/news/diplomacy/artc-aed554c6` },
            ],
          },
        ],
      },
      {
        day: `יום רביעי, 23.9`,
        items: [
          {
            tag: `אירוע`,
            title: `OECD: תחזית הביניים הכלכלית`,
            sources: [
              { label: `OECD`, url: `https://www.oecd.org/en/events/2026/09/launch-oecd-interim-economic-outlook.html` },
            ],
          },
          {
            tag: `דיון`,
            title: `ועדת הבחירות המרכזית: דיוני פסילת רשימות ומועמדים (יום 1) (09:00-20:30)`,
            sources: [
              { label: `אמס, 16.9.26`, url: `https://www.emess.co.il/radio/1929785` },
              { label: `ישראל היום, 16.9.26`, url: `https://www.israelhayom.co.il/news/law/article/21430915` },
            ],
          },
        ],
      },
      {
        day: `יום חמישי, 24.9`,
        items: [
          {
            tag: `דיון`,
            title: `ועדת הבחירות המרכזית: דיוני פסילת רשימות ומועמדים (יום 2) (09:00-17:00)`,
            sources: [
              { label: `אמס, 16.9.26`, url: `https://www.emess.co.il/radio/1929785` },
              { label: `ישראל היום, 16.9.26`, url: `https://www.israelhayom.co.il/news/law/article/21430915` },
            ],
          },
        ],
      },
      {
        day: `יום שישי, 25.9`,
        items: [
          {
            tag: `חופשה`,
            title: `25-26.9 · ערב סוכות וסוכות`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
        ],
      },
      {
        day: `יום ראשון, 27.9`,
        items: [
          {
            tag: `מועד`,
            title: `ועדת הבחירות המרכזית: אישור סופי של רשימות המועמדים`,
            sources: [
              { label: `דבר, 8.9.26`, url: `https://www.davar1.co.il/696375/` },
            ],
          },
          {
            tag: `חופשה`,
            title: `27.9-1.10 · חול המועד: אין לימודים; ימי עבודה רגילים במשק`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
        ],
      },
      {
        day: `יום שלישי, 29.9`,
        items: [
          {
            tag: `אירוע`,
            title: `OECD: Education at a Glance 2026`,
            sources: [
              { label: `OECD`, url: `https://www.oecd.org/en/events/2026/09/education-at-a-glance-2026.html` },
            ],
          },
          {
            tag: `אירוע`,
            title: `WIPO: מדד החדשנות העולמי 2026 (14:30)`,
            sources: [
              { label: `WIPO`, url: `https://www.wipo.int/en/web/global-innovation-index/w/news/2026/save-the-date-gii-2026` },
            ],
          },
          {
            tag: `אירוע`,
            title: `האו"ם: כינוס רם-דרג ליום הבינלאומי לחיסול מוחלט של נשק גרעיני`,
            sources: [
              { label: `האו"ם, כינוסים רמי-דרג במושב ה-81`, url: `https://www.un.org/en/ga/81/meetings/` },
            ],
          },
        ],
      },
      {
        day: `יום שישי, 2.10`,
        items: [
          {
            tag: `חופשה`,
            title: `2-3.10 · הושענא רבה ושמחת תורה`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
        ],
      },
      {
        day: `יום ראשון, 4.10`,
        items: [
          {
            tag: `חופשה`,
            title: `חזרה ללימודים (בחטיבות העליונות 5.10)`,
            sources: [
              { label: `משרד החינוך, מהלך שנת הלימודים תשפ"ז`, url: `https://parents.education.gov.il/gov-education/vacations-camps-leisure/schedule` },
            ],
          },
        ],
      },
    ],
  },
];
