// AUTO-GENERATED by update-sekira.py — do not edit by hand.
// Source: OneDrive…/דף מסרים/סקירה שבועית מתעדכנת לאתר.docx

export const SEKIRA_WEEK = `14–18 ביוני 2026`;

export interface SekiraEvent {
  time: string;
  committee: string;
  topic: string;
  hasPaper: boolean;
}
export interface SekiraDay { day: string; events: SekiraEvent[]; }

export const SEKIRA_PARLIAMENTARY: SekiraDay[] = [
  {
    day: `יום ראשון`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `12:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת — צפויות הצבעות`,
        hasPaper: false,
      },
      {
        time: ``,
        committee: `ועדת שרים לחקיקה`,
        topic: `חופש תנועה לישראלים בעזה; פוליטיזציה של המשפט הצבאי; קיצוץ תקציבי אקדמיה`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום שני`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `9:30`,
        committee: `ועדת הכנסת`,
        topic: `דיון בחסינות ח"כ טלי גוטליב`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום שלישי`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `9:30`,
        committee: `ועדת החינוך`,
        topic: `הפרדה מגדרית באקדמיה — קריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `10:00`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות של מתן כהנא`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום רביעי`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `9:00`,
        committee: `ועדת הביקורת`,
        topic: `עבריינות במרחב המקוון — דיון בקידום בונים מחדש`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום חמישי`,
    events: [
      {
        time: `9:30`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות של מתן כהנא`,
        hasPaper: true,
      },
    ],
  },
];

export interface SekiraHighlight { date: string; category: string; title: string; detail: string; url?: string; }

export const SEKIRA_HIGHLIGHTS: SekiraHighlight[] = [
  {
    date: `13.06–24.06`,
    category: `יום שנה`,
    title: `שנה למבצע 'עם כלביא' / מלחמת 12 הימים מול איראן`,
    detail: `המלחמה הראשונה מול איראן החלה 13.6.2025, הפסקת אש 24.6.2025`,
    url: `https://he.wikipedia.org/wiki/מבצע_עם_כלביא`,
  },
  {
    date: `14.06`,
    category: `גיאופוליטי`,
    title: `יום הולדת 80 לדונלד טראמפ`,
    detail: `נולד 14.6.1946`,
    url: `https://en.wikipedia.org/wiki/Donald_Trump`,
  },
  {
    date: `14.06`,
    category: `יום שנה`,
    title: `19 שנה להשתלטות חמאס על רצועת עזה`,
    detail: `ההשתלטות הושלמה באמצע יוני 2007`,
    url: `https://he.wikipedia.org/wiki/השתלטות_חמאס_על_רצועת_עזה`,
  },
  {
    date: `15.06`,
    category: `גיאופוליטי`,
    title: `פסגת G7`,
    detail: `לפי הדיווח ברויטרס, בכיר בממשל אמר כי כחלק מפסגת ה-G7, נשיא ארצות הברית צפוי להיפגש עם מנהיגי מדינות ערביות, כולל מצרים, איחוד האמירויות וקטר, על מנת לדון במאמצים לסיום המלחמה מול איראן. עם זאת, הבכיר הדגיש כי נתניהו אינו צפוי לקחת חלק בשיחות הללו לצד טראמפ`,
    url: `https://www.kan.org.il/content/kan-news/global/1053069/`,
  },
  {
    date: `15.06–07.07`,
    category: `גיאופוליטי`,
    title: `המושב ה-62 של מועצת זכויות האדם של האו"ם`,
    detail: `לפי האג'נדה, ידון "מצב זכויות האדם בפלסטין וטריטוריות ערביות נוספות תחת כיבוש". הדיונים במועצה עשויים להשפיע על הלחץ הדיפלומטי והמשפטי סביב ישראל, המלחמה בעזה, חמאס, והזירה הפלסטינית בכלל.`,
    url: `https://www.linkedin.com/pulse/human-rights-council-hold-62nd-session-unhumanrightscouncil-cixge`,
  },
  {
    date: `17.06`,
    category: `כלכלי`,
    title: `פד - ריבית`,
    detail: `המועד הבא שבו הפד יחליט על הריבית הוא בישיבת ה־FOMC הקרובה: שלישי–רביעי, 16–17 ביוני 2026. ההודעה על ההחלטה תפורסם ביום רביעי, 17 ביוני 2026 בשעה 14:00 שעון מזרח ארה״ב, כלומר בערך 21:00 שעון ישראל. מסיבת העיתונאים מתוכננת ל־14:30 שעון מזרח ארה״ב, כלומר 21:30 בישראל.`,
    url: `https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm`,
  },
  {
    date: `19.06`,
    category: `גיאופוליטי`,
    title: `חתימה על מזכר הבנות בין איראן לארה"ב`,
    detail: `ההסכם בין איראן לארה"ב טרם פורסם, וכל הצעדים שכלולים בו אמורים להיכנס לתוקף רק אחרי החתימה שתתקיים ביום שישי בשוויץ.`,
    url: `https://www.ynet.co.il/news/article/b1cc2gazgl`,
  },
];

export interface SekiraPoint { text: string; url?: string; }
export interface SekiraTopic { topic: string; points: SekiraPoint[]; }

export const SEKIRA_MEDIA: SekiraTopic[] = [
  {
    topic: `ביטחוני-מדיני`,
    points: [
      { text: `הסכם צפוי בין ארה"ב לאיראן — המו"מ בקו הסיום, וושינגטון מצפה לחתימה בימים הקרובים.` },
    ],
  },
  {
    topic: `פוליטי`,
    points: [
      { text: `הפריימריז בליכוד: נתניהו מקדם ועדה מסדרת במקום פריימריז — מהלך שמבקר המפלגה קבע שאינו חוקי.` },
    ],
  },
  {
    topic: `כלכלי-חברתי`,
    points: [],
  },
  {
    topic: `משפט, משטרה ופלילים`,
    points: [],
  },
  {
    topic: `ניטור שיח בימין`,
    points: [
      { text: `קמפיין הימין "אם לא נתעורר — ככה זה ייגמר": בהלה מתרחיש שבו ממשלת בנט-איזנקוט סוגרת את ערוץ 14 ועוצרת על התבטאויות ברשת.`, url: `https://www.facebook.com/reel/1292864122883836/` },
    ],
  },
  {
    topic: `עולמי`,
    points: [],
  },
];
