// AUTO-GENERATED by update-sekira.py — do not edit by hand.
// Source: OneDrive…/דף מסרים/סקירה שבועית מתעדכנת לאתר.docx

export const SEKIRA_WEEK = `21–25 ביוני 2026`;

export interface SekiraEvent {
  time: string;
  committee: string;
  topic: string;
  hasPaper: boolean;
}
export interface SekiraDay { day: string; events: SekiraEvent[]; }

export const SEKIRA_PARLIAMENTARY: SekiraDay[] = [
  {
    day: `יום ראשון`,
    events: [
      {
        time: `09:00`,
        committee: `ועדת החוקה`,
        topic: `פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `10:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת (שידורים) — הנמקת הסתייגויות והצבעות`,
        hasPaper: false,
      },
      {
        time: `10:00`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות (חוק איסור הונאה בכשרות, תיקון מס' 5)`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום שני`,
    events: [
      {
        time: `09:00`,
        committee: `ועדת החוקה`,
        topic: `חקיקת הבחירות לכנסת ה-26 — פניית יו"ר ועדת הבחירות המרכזית`,
        hasPaper: true,
      },
      {
        time: `10:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת (שידורים) — המשך הסתייגויות והצבעות`,
        hasPaper: false,
      },
      {
        time: `11:30`,
        committee: `ועדת החוקה`,
        topic: `פיצול היועמ"ש — המשך הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `12:45`,
        committee: `הוועדה לביטחון לאומי`,
        topic: `הדרישה להוציא את רע"מ מחוץ לחוק (מנסור עבאס)`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום שלישי`,
    events: [
      {
        time: `09:00`,
        committee: `ועדת החוקה`,
        topic: `פיצול היועמ"ש — המשך הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `10:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת (שידורים) — המשך הסתייגויות והצבעות`,
        hasPaper: false,
      },
      {
        time: `10:00`,
        committee: `ועדת החינוך`,
        topic: `הצעת חוק רשות המורשת ביהודה והשומרון`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום רביעי`,
    events: [
      {
        time: `09:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת (שידורים) — המשך הסתייגויות והצבעות`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום חמישי`,
    events: [
      {
        time: `10:00`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות — המשך דיון (תיקון מס' 5)`,
        hasPaper: true,
      },
      {
        time: `12:00`,
        committee: `ועדת החינוך`,
        topic: `מענים חינוכיים לנוער נושר בחוות ביהודה ושומרון`,
        hasPaper: false,
      },
    ],
  },
];

export interface SekiraHighlight { day: string; date: string; category: string; title: string; detail: string; url?: string; }

export const SEKIRA_HIGHLIGHTS: SekiraHighlight[] = [
  {
    day: `יום ראשון`,
    date: `21.06`,
    category: `בג"ץ`,
    title: `הצבעה חוזרת על בחירת מבקר המדינה`,
    detail: `בג"ץ הציע לכנסת הצבעה חוזרת על בחירת מבקר המדינה, על רקע פגיעה בחשאיות ההצבעה וטענת ניגוד עניינים — והצדדים נדרשו להשיב עד יום ראשון.`,
    url: `https://www.ynet.co.il/news/blogs/article/bk9fpz11zgx`,
  },
  {
    day: `יום חמישי`,
    date: `25.06`,
    category: `פוליטי`,
    title: `שנתיים לפסיקת בג"ץ - גיוס חרדים`,
    detail: ``,
  },
];

export interface SekiraPoint { heading?: string; text: string; url?: string; }
export interface SekiraTopic { topic: string; points: SekiraPoint[]; }

export const SEKIRA_MEDIA: SekiraTopic[] = [
  {
    topic: `ביטחוני-מדיני`,
    points: [
      { heading: `הסכם איראן נתקע בלבנון`, text: `שיחות ההמשך על מזכר ההבנות בין ארה"ב לאיראן נדחו על רקע התלקחות חילופי האש בין ישראל לחיזבאללה — וההסדרה האזורית מתנגשת עם המציאות בצפון.`, url: `https://13tv.co.il/item/news/politics/state-policy/iran-5-905224718/` },
      { heading: `הטנקיסטיות יורדות מהשריון`, text: `ראשי ישיבות ההסדר הודיעו שלא ישלחו תלמידים לחיל בעקבות שילוב נשים בשריון — ויכוח על מי קובע את גבולות השירות, הצבא או המגזרים.`, url: `https://www.mako.co.il/news-military/2026_q2/Article-e3110571f40be91027.htm` },
      { heading: `חמישה לוחמים נפלו בדרום לבנון`, text: `הותר לפרסום נפילתם בתקרית — תזכורת למחיר הדמים של המשך הלחימה בצפון.`, url: `https://www.maariv.co.il/news/military/article-1335282` },
    ],
  },
  {
    topic: `פוליטי`,
    points: [
      { heading: `לחץ חרדי על משרד החינוך`, text: `מנהל המחוז החרדי שי קלדרון זומן לשימוע לפני פיטורים ברקע לחץ פוליטי חרדי — אכיפת לימודי ליבה ופיקוח תקציבי מול כוח פוליטי מאורגן.`, url: `https://www.srugim.co.il/101004527-%D7%91%D7%92%D7%9C%D7%9C-%D7%94%D7%9E%D7%9C%D7%97%D7%9E%D7%94-%D7%91%D7%A9%D7%97%D7%99%D7%AA%D7%95%D7%AA-%D7%94%D7%97%D7%A8%D7%93%D7%99%D7%AA-%D7%9E%D7%A0%D7%94%D7%9C-%D7%94%D7%9E%D7%97%D7%95%D7%96` },
      { heading: `טלטלה בליכוד סביב הפריימריז`, text: `יועמ"ש המפלגה עו"ד אבי הלוי סיים תפקיד אחרי כ-30 שנה, בצל פרשת הזיופים והמחלוקות סביב הוועידה והבחירות הפנימיות.`, url: `https://news.walla.co.il/item/3846917` },
    ],
  },
  {
    topic: `כלכלי-חברתי`,
    points: [],
  },
  {
    topic: `משפט, משטרה ופלילים`,
    points: [
      { heading: `סולברג מסמן לבן גביר גבול`, text: `יו"ר ועדת הבחירות המרכזית הורה בעבר לבן גביר להסיר סרטונים שצולמו בנכסי ציבור וקבע שמדובר בתעמולת בחירות אסורה — הגבול בין שר מכהן לקמפיין.`, url: `https://www.kan.org.il/content/kan-news/politic/1058254/` },
      { heading: `מבקר המדינה — בג"ץ הוציא צו על תנאי`, text: `בג"ץ ביקש מהכנסת לשקול הצבעה חוזרת על בחירת עו"ד מיכאל ראבילו למבקר המדינה.`, url: `https://www.inn.co.il/news/699441` },
      { heading: `המשטרה והפגנות רחביה`, text: `לפי "הארץ", המשטרה עודדה שכנים של נתניהו לעתור לבג"ץ להגבלת הפגנות השבת ברחביה — רתימת הליך משפטי לצמצום המחאה.`, url: `https://www.haaretz.co.il/news/law/2026-06-21/ty-article/.premium/0000019e-e523-d2b1-a5bf-ff3702bd0000` },
    ],
  },
  {
    topic: `ניטור שיח בימין`,
    points: [
      { heading: `סדקים בברית עם הימין`, text: `חילופי הדברים בין סגן הנשיא ואנס לינון מגל, וכעת שיתוף מאמר של טראמפ נגד נתניהו, מעידים על מתח גובר בין ממשל טראמפ לימין הישראלי על רקע ההסכם מול איראן.`, url: `https://www.mako.co.il/news-world/2026_q2/Article-bfcafad7a85ee91027.htm` },
    ],
  },
  {
    topic: `עולמי`,
    points: [],
  },
];
