// AUTO-GENERATED by update-sekira.py — do not edit by hand.
// Source: OneDrive…/דף מסרים/סקירה שבועית מתעדכנת לאתר.docx

export const SEKIRA_WEEK = `14–18 ביוני 2026`;

export interface SekiraEvent {
  time: string;
  committee: string;
  topic: string;
  hasPaper: boolean;
}
export interface SekiraDay { day: string; events: SekiraEvent[]; }

export const SEKIRA_PARLIAMENTARY: SekiraDay[] = [
  {
    day: `יום ראשון`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `12:00`,
        committee: `ועדת התקשורת`,
        topic: `הצעת חוק התקשורת — צפויות הצבעות`,
        hasPaper: true,
      },
      {
        time: ``,
        committee: `ועדת שרים לחקיקה`,
        topic: `חופש תנועה לישראלים בעזה; פוליטיזציה של המשפט הצבאי; קיצוץ תקציבי אקדמיה`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום שני`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `9:30`,
        committee: `ועדת הכנסת`,
        topic: `דיון בחסינות ח"כ טלי גוטליב`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום שלישי`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `9:30`,
        committee: `ועדת החינוך`,
        topic: `הפרדה מגדרית באקדמיה — קריאה שנייה ושלישית`,
        hasPaper: false,
      },
      {
        time: `10:00`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות של מתן כהנא`,
        hasPaper: false,
      },
    ],
  },
  {
    day: `יום רביעי`,
    events: [
      {
        time: `9:00`,
        committee: `ועדת החוקה`,
        topic: `חוק פיצול היועמ"ש — הכנה לקריאה שנייה ושלישית`,
        hasPaper: true,
      },
      {
        time: `9:00`,
        committee: `ועדת הביקורת`,
        topic: `עבריינות במרחב המקוון — דיון בקידום בונים מחדש`,
        hasPaper: true,
      },
    ],
  },
  {
    day: `יום חמישי`,
    events: [
      {
        time: `9:30`,
        committee: `הוועדה למיזמים ציבוריים`,
        topic: `ביטול הרפורמה בכשרות של מתן כהנא`,
        hasPaper: false,
      },
    ],
  },
];

export interface SekiraHighlight { date: string; title: string; detail: string; }

export const SEKIRA_HIGHLIGHTS: SekiraHighlight[] = [
  {
    date: `13–24.06`,
    title: `שנה למבצע "עם כלביא" — מלחמת 12 הימים מול איראן`,
    detail: `המלחמה הראשונה מול איראן (13.6–24.6.2025)`,
  },
  {
    date: `14.06`,
    title: `יום הולדת 80 לדונלד טראמפ`,
    detail: `נולד 14.6.1946`,
  },
  {
    date: `14.06`,
    title: `19 שנה להשתלטות חמאס על רצועת עזה`,
    detail: `ההשתלטות הושלמה באמצע יוני 2007`,
  },
  {
    date: `15.06`,
    title: `פסגת G7`,
    detail: ``,
  },
  {
    date: `17.06`,
    title: `פד — החלטת ריבית`,
    detail: ``,
  },
];

export interface SekiraPoint { text: string; url?: string; }
export interface SekiraTopic { topic: string; points: SekiraPoint[]; }

export const SEKIRA_MEDIA: SekiraTopic[] = [
  {
    topic: `ביטחוני-מדיני`,
    points: [
      { text: `הסכם צפוי בין ארה"ב לאיראן — המו"מ בקו הסיום, וושינגטון מצפה לחתימה בימים הקרובים.` },
    ],
  },
  {
    topic: `פוליטי`,
    points: [
      { text: `הפריימריז בליכוד: נתניהו מקדם ועדה מסדרת במקום פריימריז — מהלך שמבקר המפלגה קבע שאינו חוקי.` },
    ],
  },
  {
    topic: `כלכלי-חברתי`,
    points: [],
  },
  {
    topic: `משפט, משטרה ופלילים`,
    points: [],
  },
  {
    topic: `ניטור שיח בימין`,
    points: [
      { text: `קמפיין הימין "אם לא נתעורר — ככה זה ייגמר": בהלה מתרחיש שבו ממשלת בנט-איזנקוט סוגרת את ערוץ 14 ועוצרת על התבטאויות ברשת.`, url: `https://www.facebook.com/reel/1292864122883836/` },
    ],
  },
  {
    topic: `עולמי`,
    points: [],
  },
];
